-- ============================================================
--  Course tags
--
--  Tags are generated by the curriculum model from a fixed
--  vocabulary (see aretay-admin/lib/tags.ts) and denormalized
--  here from curriculum.tags so the catalog can be filtered
--  without parsing jsonb. Always written through the admin API,
--  which sanitizes against the canonical taxonomy.
-- ============================================================

alter table courses
  add column if not exists tags text[] not null default '{}';

create index if not exists courses_tags_idx
  on courses using gin(tags);
